// Exercise data organized by rehabilitation phase
// Based on evidence-based protocols for radial head fracture rehabilitation

export const INJURY_INFO = {
  title: 'Fractura de Cabeza del Radio',
  subtitle: 'Brazo izquierdo — Post-inmovilización de 1 mes',
  anatomy: {
    title: 'Anatomía de la Lesión',
    content: 'La cabeza del radio es la porción proximal del hueso radio que se articula con el cóndilo del húmero (articulación humeroradial) y con la escotadura radial del cúbito (articulación radiocubital proximal). Es fundamental para dos movimientos: la flexo-extensión del codo y la prono-supinación del antebrazo.',
  },
  immobilization: {
    title: 'Efectos de 1 Mes de Inmovilización',
    items: [
      { label: 'Adhesión capsular', desc: 'La cápsula articular se retrae y pierde elasticidad, generando rigidez especialmente en extensión completa.' },
      { label: 'Atrofia muscular', desc: 'El tríceps braquial, supinador y bíceps pierden masa y fuerza, debilitando los movimientos de extensión y supinación.' },
      { label: 'Fibrosis periarticular', desc: 'Se forma tejido cicatricial alrededor de la articulación que limita el rango de movimiento (ROM).' },
      { label: 'Pérdida propioceptiva', desc: 'La articulación pierde la capacidad de "sentir" su posición, aumentando el riesgo de movimientos compensatorios.' },
    ],
  },
  criticalMovements: {
    title: 'Movimientos Prioritarios',
    extension: {
      label: 'Extensión del Codo',
      severity: 'Crítico',
      explanation: 'La extensión completa es el movimiento más afectado. La cápsula anterior se retrae durante la inmovilización en flexión, y la cabeza del radio fracturada limita el deslizamiento fisiológico. Es frecuente un déficit de 15-30° respecto al rango normal.',
    },
    supination: {
      label: 'Supinación del Antebrazo',
      severity: 'Crítico',
      explanation: 'La supinación depende directamente de la rotación de la cabeza del radio sobre el cóndilo humeral. Tras la fractura, el callo óseo y la inflamación residual pueden bloquear mecánicamente este movimiento. Es el más lento en recuperarse.',
    },
    flexion: {
      label: 'Flexión del Codo',
      severity: 'Moderado',
      explanation: 'Se recupera de forma más rápida al ser favorecida por la gravedad y la musculatura bicipital. El déficit suele ser menor (5-15°).',
    },
    pronation: {
      label: 'Pronación del Antebrazo',
      severity: 'Moderado',
      explanation: 'Se ve menos afectada que la supinación porque la membrana interósea ayuda a distribuir la fuerza rotacional. Se recupera más fácilmente con ejercicios activos.',
    },
  },
  timeline: [
    { week: '1-2', phase: 'Movilización pasiva', desc: 'Recuperar rango articular sin carga. Movimientos guiados por gravedad o por la otra mano.' },
    { week: '3-4', phase: 'Activo-asistido', desc: 'Comenzar movimiento activo con asistencia. Ejercicios isométricos suaves para activar musculatura.' },
    { week: '5-8', phase: 'Activo resistido', desc: 'Ejercicios con resistencia progresiva (bandas elásticas, pesos ligeros). Recuperación funcional.' },
    { week: '8-12', phase: 'Fortalecimiento', desc: 'Cargas progresivas y ejercicios funcionales para volver a la actividad normal.' },
  ],
}

export const EXERCISES = [
  // Phase 1: Weeks 1-2 — Passive ROM
  {
    id: 'pendulum',
    phase: 1,
    phaseLabel: 'Fase 1 — Pasivo',
    name: 'Ejercicio Pendular de Codo',
    target: 'Extensión / Flexión',
    sets: '3 series',
    reps: '10-15 oscilaciones',
    difficulty: 1,
    description: 'Movilización pasiva asistida por gravedad para ganar rango articular sin forzar la articulación.',
    steps: [
      'Inclínate hacia adelante con el brazo afectado colgando libremente.',
      'Deja que la gravedad estire suavemente el codo hacia la extensión.',
      'Realiza movimientos pendulares lentos: adelante-atrás y en círculos.',
      'Mantén el hombro relajado, no fuerces el codo.',
      'Cada oscilación debe durar 3-4 segundos. Sin dolor.',
    ],
  },
  {
    id: 'gravity-extension',
    phase: 1,
    phaseLabel: 'Fase 1 — Pasivo',
    name: 'Extensión Asistida por Gravedad',
    target: 'Extensión',
    sets: '5 repeticiones',
    reps: '30 segundos cada una',
    difficulty: 1,
    description: 'Estiramiento pasivo de la cápsula anterior del codo usando el peso del brazo.',
    steps: [
      'Siéntate con el codo apoyado sobre una mesa o cojín firme, con la muñeca colgando por el borde.',
      'Coloca una toalla enrollada bajo el codo para elevarlo ligeramente.',
      'Deja que la gravedad extienda el codo lentamente durante 30 segundos.',
      'No empujes con la otra mano: deja que el peso del antebrazo haga el trabajo.',
      'Descansa 15 segundos entre repeticiones.',
    ],
  },
  {
    id: 'passive-supination',
    phase: 1,
    phaseLabel: 'Fase 1 — Pasivo',
    name: 'Supinación Pasiva con Mano Contraria',
    target: 'Supinación',
    sets: '4 series',
    reps: '8-10 repeticiones',
    difficulty: 1,
    description: 'Rotación externa del antebrazo guiada suavemente por la mano sana.',
    steps: [
      'Siéntate con el codo del brazo afectado pegado al cuerpo, flexionado a 90°.',
      'Sujeta la muñeca del brazo afectado con la mano sana.',
      'Gira el antebrazo lentamente hacia la supinación (palma hacia arriba).',
      'Mantén 5 segundos en el rango máximo sin dolor.',
      'Vuelve lentamente a la posición neutra. No fuerces.',
    ],
  },
  {
    id: 'flexion-passive',
    phase: 1,
    phaseLabel: 'Fase 1 — Pasivo',
    name: 'Flexión Pasiva Asistida',
    target: 'Flexión',
    sets: '3 series',
    reps: '10 repeticiones',
    difficulty: 1,
    description: 'Recuperar el rango de flexión usando la mano contraria como guía.',
    steps: [
      'Siéntate con el brazo afectado apoyado sobre una mesa.',
      'Con la mano sana, empuja suavemente el antebrazo hacia la flexión.',
      'Mantén 3-5 segundos al final del rango.',
      'Vuelve lentamente a la posición inicial.',
      'El movimiento debe ser lento y controlado, sin rebotes.',
    ],
  },

  // Phase 2: Weeks 3-4 — Active-Assisted
  {
    id: 'wall-slide-ext',
    phase: 2,
    phaseLabel: 'Fase 2 — Activo-Asistido',
    name: 'Deslizamiento en Pared para Extensión',
    target: 'Extensión',
    sets: '3 series',
    reps: '12 repeticiones',
    difficulty: 2,
    description: 'Extensión activa con apoyo en pared para asistir el movimiento.',
    steps: [
      'De pie frente a una pared, coloca la palma del brazo afectado contra la pared a la altura del hombro.',
      'Desliza la mano hacia arriba lentamente, extendiendo el codo progresivamente.',
      'Mantén la posición extendida 3 segundos.',
      'Vuelve lentamente a la posición inicial.',
      'Aumenta la distancia a la pared para mayor extensión.',
    ],
  },
  {
    id: 'towel-supination',
    phase: 2,
    phaseLabel: 'Fase 2 — Activo-Asistido',
    name: 'Supinación con Toalla',
    target: 'Supinación',
    sets: '3 series',
    reps: '10 repeticiones',
    difficulty: 2,
    description: 'Movimiento de "escurrir toalla" para trabajar la supinación activa.',
    steps: [
      'Sujeta una toalla pequeña con ambas manos, codo pegado al cuerpo a 90°.',
      'Gira la mano del brazo afectado hacia la supinación (como escurriendo la toalla).',
      'La mano sana opone una ligera resistencia.',
      'Mantén 3 segundos y vuelve a la posición neutra.',
      'Aumenta la resistencia gradualmente con los días.',
    ],
  },
  {
    id: 'isometric-ext',
    phase: 2,
    phaseLabel: 'Fase 2 — Activo-Asistido',
    name: 'Isométrico de Extensión',
    target: 'Extensión',
    sets: '4 series',
    reps: '6 segundos × 8 rep',
    difficulty: 2,
    description: 'Contracción estática del tríceps contra resistencia fija para activar la musculatura sin movimiento articular.',
    steps: [
      'Coloca la palma de la mano del brazo afectado contra la parte inferior de una mesa.',
      'Intenta empujar la mesa hacia abajo (extensión), pero la mesa impide el movimiento.',
      'Mantén la contracción 6 segundos al 50-60% de tu fuerza máxima.',
      'Descansa 5 segundos entre repeticiones.',
      'No debe haber dolor. Si lo hay, reduce la intensidad.',
    ],
  },
  {
    id: 'pronation-active',
    phase: 2,
    phaseLabel: 'Fase 2 — Activo-Asistido',
    name: 'Pronación Activa con Bastón',
    target: 'Pronación',
    sets: '3 series',
    reps: '12 repeticiones',
    difficulty: 2,
    description: 'Rotación interna del antebrazo usando un bastón o palo como palanca.',
    steps: [
      'Sujeta un bastón o palo de escoba con la mano del brazo afectado.',
      'Codo pegado al cuerpo a 90°.',
      'Gira el bastón hacia la pronación (palma hacia abajo) de forma activa.',
      'La mano sana sujeta el otro extremo para guiar el movimiento.',
      'Vuelve lentamente a posición neutra.',
    ],
  },

  // Phase 3: Weeks 5+ — Active Resisted
  {
    id: 'theraband-supination',
    phase: 3,
    phaseLabel: 'Fase 3 — Resistido',
    name: 'Supinación con Banda Elástica',
    target: 'Supinación',
    sets: '3 series',
    reps: '12-15 repeticiones',
    difficulty: 3,
    description: 'Fortalecimiento del supinador y bíceps contra resistencia elástica progresiva.',
    steps: [
      'Ata una banda elástica a un punto fijo a la altura del codo.',
      'Sujeta la banda con la mano del brazo afectado, codo a 90°.',
      'Gira el antebrazo hacia la supinación contra la resistencia de la banda.',
      'Control total: 2 segundos en la ida, 3 segundos en la vuelta (excéntrico).',
      'Progresa de banda ligera a media cuando completes 15 reps sin dolor.',
    ],
  },
  {
    id: 'eccentric-extension',
    phase: 3,
    phaseLabel: 'Fase 3 — Resistido',
    name: 'Extensión Excéntrica con Mancuerna',
    target: 'Extensión',
    sets: '3 series',
    reps: '10 repeticiones',
    difficulty: 3,
    description: 'Fortalecimiento del tríceps en fase excéntrica (el músculo se alarga bajo carga).',
    steps: [
      'Siéntate con una mancuerna ligera (0.5-1 kg) en la mano del brazo afectado.',
      'Usa la mano sana para ayudar a llevar el brazo a extensión completa (fase concéntrica asistida).',
      'Desde la extensión, baja la mancuerna lentamente (4-5 segundos) hacia la flexión.',
      'Esta fase lenta y controlada es la parte terapéutica del ejercicio.',
      'No hay dolor agudo. Una ligera molestia es aceptable.',
    ],
  },
  {
    id: 'wrist-supination-weight',
    phase: 3,
    phaseLabel: 'Fase 3 — Resistido',
    name: 'Supinación con Peso Descentrado',
    target: 'Supinación',
    sets: '3 series',
    reps: '10 repeticiones por lado',
    difficulty: 3,
    description: 'Fortalecimiento avanzado de supinación usando un martillo o herramienta con peso descentrado.',
    steps: [
      'Sujeta un martillo o pesa con mango por la mano afectada.',
      'Codo a 90° pegado al cuerpo.',
      'Gira el antebrazo lentamente hacia la supinación contra la resistencia del peso.',
      'Mantén 2 segundos en supinación máxima.',
      'Vuelve lentamente a neutro. Progresa aumentando la distancia al peso.',
    ],
  },
  {
    id: 'full-rom-combined',
    phase: 3,
    phaseLabel: 'Fase 3 — Resistido',
    name: 'ROM Completo Combinado',
    target: 'Todos los movimientos',
    sets: '3 series',
    reps: '8 ciclos completos',
    difficulty: 3,
    description: 'Ejercicio funcional que integra flexión, extensión, pronación y supinación en un solo movimiento fluido.',
    steps: [
      'De pie, brazo afectado a lo largo del cuerpo con una botella de agua (0.5L).',
      'Flexiona el codo llevando la botella al hombro (flexión + supinación).',
      'Extiende el brazo hacia adelante como para servir agua (extensión + pronación).',
      'Vuelve a la posición inicial siguiendo la secuencia inversa.',
      'Cada ciclo completo debe durar 6-8 segundos. Movimiento fluido y controlado.',
    ],
  },
]
